[New Rule] jsx-embed-condition
jsx-eslint/eslint-plugin-react pull request #2888
Opened 2020-12-26 14:42 UTC by steelbrain

This rule disallows use of `&&` inside JSX Embeds to avoid conditional numbers from being rendered.

2020-12-26 17:36 UTC, ljharb requested changes
I'm still not convinced this is a rule worth adding. If it were added, it'd need autofix to avoid being too disruptive.

2020-12-26 17:36 UTC, ljharb commented on lib/rules/jsx-embed-condition.js
> +            'Using && to condition JSX embeds is forbidden. Convert it to a ternary operation instead'
```suggestion
          message: 'Using && to condition JSX embeds is forbidden. Convert it to a ternary operation instead'
```
this looks suspiciously like terrible prettier-style indentation :-/ please don't run prettier on repos that don't have it configured.

2020-12-26 17:36 UTC, ljharb commented on tests/lib/rules/jsx-embed-condition.js
> +  // Is the parser out of date
no, but you can specify the `parserOptions.ecmaVersion` to be `2020` in this test case.

2020-12-27 01:14 UTC, steelbrain commented
> I'm still not convinced this is a rule worth adding

It is a convention recommended by [The official React docs](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator). A whole bunch of people have been stung by this bug, many didn't even know what caused it, see:

- https://github.com/facebook/react-native/issues/20764
- https://github.com/facebook/react-native/issues/23607
- https://github.com/facebook/react-native/issues/23735
- https://github.com/artsy/emission/pull/1706
- https://blog.echobind.com/a-common-conditional-rendering-bug-in-react-native-8bbbc400abd8

(and you'll find many more examples by searching for "Text strings must be rendered within a Text component" on Google)

Apart from crashing React Native hard, the bug is known to add random `0`s to the DOM in HTML renderer. I wrote this PR because my team got bit by this a few times.

> If it were added, it'd need autofix to avoid being too disruptive.

This Lint rule is opt-in only. I can commit to adding an autofix for it later next month. My work schedule is pretty tight before that.

> you can specify the parserOptions.ecmaVersion to be 2020 in this test case.

Doing so fixed the check on tests for latest Node.js runners, but broke them on the rest. I looked around the repository and couldn't find any tests with `ecmaVersion` newer than 2018. I would appreciate some help here! Thanks!

2020-12-29 00:27 UTC, ljharb commented on tests/lib/rules/jsx-embed-condition.js
> +  // Is the parser out of date
to clarify, i meant in this *one test case*, not for all test cases.

2020-12-29 00:28 UTC, ljharb commented
You can pass `parserOptions.ecmaVersion` directly in the one test case.

2020-12-29 02:35 UTC, steelbrain commented
> You can pass parserOptions.ecmaVersion directly in the one test case.

Attempted in https://github.com/yannickcr/eslint-plugin-react/pull/2888/commits/8abb5dcd900845d416f4469d7fc2fbf9197c4040 No dice. Any other ideas?

2020-12-29 11:58 UTC, haroldwaste approved these changes

2020-12-29 22:19 UTC, ljharb reviewed
I've rebased and hopefully fixed the tests. I'm not sold on the name of the rule - "embeds" isn't a term I've ever heard before to describe jsx curly-brace expressions.

Specifically, this is a rule concerned with preventing accidental *rendering* of a zero. This can happen only in the "children" position in jsx, or in a `React.createElement` call.

So:
 - let's add support for `React.createElement`, both in the `children` position and in a literal `children` prop passed to that function
 - let's rename the rule. perhaps, since it's no longer just jsx, `no-conditional-children`?

2020-12-30 00:34 UTC, ljharb commented
Please mark the PR as ready for review once the next round of changes is done. Thanks!

2021-01-04 01:56 UTC, duncanbeevers commented
We have a similar rule in an internal codebase called `logical-and-expressions`; its existence in our jsx-ruleset makes it clear what its scope is.

Since this plugin's purview is a bit broader, perhaps a name like `jsx-logical-and-expressions` would capture the rule's scope+spirit.

2021-01-04 19:05 UTC, duncanbeevers commented
@steelbrain Here's the internal rule we use, which includes a simple fixer.

```js
module.exports = {
  meta: {
    docs: {
      url: 'SECRET URL'
    },
    fixable: 'code'
  },
  create(context) {
    const sourceCode = context.getSourceCode();

    return {
      JSXExpressionContainer(node) {
        if (
          node.expression.type === 'LogicalExpression' &&
          node.expression.operator === '&&' &&
          node.parent.type !== 'JSXAttribute'
        ) {
          context.report({
            node,
            message: 'JSX expression should not use logical-and.',
            fix: (fixer) => fixer.replaceText(
              node,
              `{${sourceCode.getText(node.expression.left)} ? ${sourceCode.getText(node.expression.right)} : null}`
            )
          });
        }
      }
    };
  }
};
```

2021-01-04 19:16 UTC, steelbrain commented
I do not have the bandwidth to work on it this week, I'll continue this work on the weekend. Thank you for your continued support!

2021-12-07 15:18 UTC, Dakuan commented
We've also been bit by this bug and would like to see this rule enforced in our code base

2022-06-29 17:09 UTC, ljharb commented
@steelbrain are you still planning to finish this?

2022-06-29 21:40 UTC, holic commented
@ljharb Happy to open up a new PR with the lint rule + fix + tests if ya'll are interested in this. I was gonna release it as a separate package otherwise.

2022-06-29 23:07 UTC, steelbrain commented
I do not have the bandwidth in the near future and this needs more love than I can give right now :)
Good luck @holic

2022-06-29 23:16 UTC, ljharb commented
Let's please keep this open so it can be reused.

2022-06-29 23:16 UTC, ljharb commented
@holic please post a branch link here, and i'll update the PR

2022-07-02 17:55 UTC, holic commented
Added a PR here: https://github.com/jsx-eslint/eslint-plugin-react/pull/3318

This ports over the code we used internally at my last company that I was intending to release as its own package. Let me know if you'd prefer I build off of this PR instead.

2022-07-02 21:07 UTC, ljharb commented
@holic i thought i was pretty clear i did *not* want a second PR opened; that pollutes the repo forever. Now I have to keep both PRs open and in sync until both are landed together.

2022-12-20 07:48 UTC, steelbrain commented
Closed by https://github.com/jsx-eslint/eslint-plugin-react/pull/3203

2022-12-20 07:48 UTC, closed without merging