Replace createClass in sort-comp examples with class component
jsx-eslint/eslint-plugin-react pull request #3339
Opened 2022-07-15 22:20 UTC by maurer2

2022-07-15 22:24 UTC, ljharb requested changes
Rather than replacing these examples, let's add them so we have both

2022-07-15 22:24 UTC, ljharb commented on docs/rules/sort-comp.md
> +  render(){
```suggestion
  render () {
```

2022-07-15 22:24 UTC, ljharb commented on docs/rules/sort-comp.md
> +  render(){
```suggestion
  render () {
```

2022-07-15 22:24 UTC, ljharb commented on docs/rules/sort-comp.md
> +  onClick = () => {}
functions should never be stored in class fields
```suggestion
  onClick = this.onClick.bind(this);
  onClick() {}
```

2022-07-15 22:24 UTC, ljharb commented on docs/rules/sort-comp.md
> +  onClick = () => {}
same here

2022-07-16 00:06 UTC, maurer2 commented
Okay, I restored the `createClass` examples and fixed the formatting issues.
Cheers

2022-07-16 00:26 UTC, ljharb commented on docs/rules/sort-comp.md
> +  render () {
```suggestion
  render() {
```
whoops, sorry, i think i spaced it wrong in my original suggestion. same throughout.

2022-07-16 01:33 UTC, maurer2 commented
Implemented the onClick changes, but I think `onClick = this.onClick.bind(this);` needs to be in the constructor. Public class fields should also work as an alternative.

2022-07-16 18:14 UTC, ljharb approved these changes
Thanks!

2022-07-16 20:30 UTC, merged