[Fix] `jsx-no-leaked-render`: autofix nested "&&" logical expressions
jsx-eslint/eslint-plugin-react pull request #3353
Opened 2022-08-10 12:14 UTC by hduprat

Fixes #3323

2022-08-10 16:04 UTC, Belco90 requested changes
LGTM! Could you add the scenarios reported in #3323 as valid tests? So it's clear that those cases have been fixed.

2022-08-10 17:01 UTC, ljharb requested changes
Looks great, but could we add the test case from the OP of the linked issue?

2022-08-10 17:01 UTC, ljharb commented on lib/rules/jsx-no-leaked-render.js
> +  return op.concat(extractExpressionBetweenLogicalAnds(node.left), extractExpressionBetweenLogicalAnds(node.right));
```suggestion
  return [].concat(
    extractExpressionBetweenLogicalAnds(node.left),
    extractExpressionBetweenLogicalAnds(node.right)
  );
```

2022-08-12 12:35 UTC, hduprat commented on lib/rules/jsx-no-leaked-render.js
> +  return op.concat(extractExpressionBetweenLogicalAnds(node.left), extractExpressionBetweenLogicalAnds(node.right));
@ljharb it's done now

2022-08-12 13:36 UTC, Belco90 approved these changes

2022-08-12 17:54 UTC, ljharb approved these changes

2022-08-13 06:23 UTC, merged