no-unstable-nested-components: Add to recommended rules
jsx-eslint/eslint-plugin-react pull request #3444
Opened 2022-09-29 16:37 UTC by eps1lon

The issue this rule catches is a very common beginner issue that requires understanding of the reconciler. Ideally this issue wouldn't exist but until then let's make sure you start out with a linter that catches these issues.

I adjusted the docs to no longer recommend memoizing nested components but and document migration strategies.

/cc @gaearon

2022-09-29 16:38 UTC, ljharb requested changes
Adding anything to a shared config is a semver-major change, so it's unlikely to land any time soon. I'd love to land the docs updates separately tho!

2022-09-29 16:41 UTC, eps1lon commented
> Adding anything to a shared config is a semver-major change, so it's unlikely to land any time soon. I'd love to land the docs updates separately tho!

Gotcha. Let's discuss the docs changes then and I'll file the semver-major separately.

2022-09-29 16:41 UTC, gaearon commented
Should we just add this logic to rules of Hooks?

2022-09-29 17:32 UTC, ljharb commented
@gaearon if it's hook-related then it definitely makes sense.

2022-09-30 04:53 UTC, AriPerkkio commented on docs/rules/no-unstable-nested-components.md
> +React reconciliation performs element type comparison with [reference equality](https://reactjs.org/docs/reconciliation.html#elements-of-different-types). The reference to the same element changes on
> `[possible bugs are introduced](https://codepen.io/ariperkkio/pen/vYLodLB)`

I'll update this demo not to include `useCallback` example at some point.

2022-09-30 04:58 UTC, AriPerkkio commented
If I remember right this is the line that allows memoized nested components:

https://github.com/jsx-eslint/eslint-plugin-react/blob/2575bba0ae30b1b0b4013539be3b0dc4eb8114eb/lib/rules/no-unstable-nested-components.js#L435-L436

This was clearly a mistake in the rule's initial design. `useCallback` etc. don't guarantee the component is actually created just once. And moving the component out of the render block should always be the first step to recommend.

2022-10-07 17:06 UTC, ljharb approved these changes

2022-10-07 18:29 UTC, merged