[FIX] when forwardRef and memo nested, prop-types incorrect
jsx-eslint/eslint-plugin-react pull request #3679
Opened 2024-01-14 13:52 UTC by developer-bandi

Fix #3521

- Modified to allow an exception that skips the type check of memo when forwardRef and memo are nested.
- forwardRef, memo, forwardRef with memo testcase add

2024-01-15 06:41 UTC, ljharb approved these changes

2024-01-15 07:07 UTC, ljharb commented
With the latest rebase, some tests are failing. Can you update to this commit and take a look?

2024-01-15 15:20 UTC, developer-bandi commented
yes, so I fix the failed test code but almost code is changed. so may be reivew is nessesary

and some Tests are fail because node install fail. i don't know why it is fail. please tell me hint to fix it. (and Automatic Rebase)

2024-01-15 18:35 UTC, ljharb requested changes
You don't have to worry about the automatic rebase check. The PR now lacks any tests, is that intentional?

2024-01-15 18:35 UTC, ljharb commented on lib/rules/prop-types.js
> +            && innerComponent.node.range[0] === component.node.arguments[0].range[0]);
```suggestion
      if (componentIsMemo && argumentIsForwardRef) {
        const forwardComponent = list.find(
          (innerComponent) => (
            innerComponent.node.range[0] === component.node.arguments[0].range[0]
            && innerComponent.node.range[0] === component.node.arguments[0].range[0]
        );
```

2024-01-16 01:42 UTC, developer-bandi commented
> You don't have to worry about the automatic rebase check. The PR now lacks any tests, is that intentional?

no, it is not intentional. it's my mistake. perhaps i did 풀 at local codebase, that test code is deleted.
so i revert all test code already exist

2024-01-21 12:46 UTC, developer-bandi commented
@ljharb 
Is there anything additional I need to do to merge this pr?

2024-02-18 03:48 UTC, ljharb approved these changes

2024-02-18 07:16 UTC, merged